# Generated by Django 4.1.3 on 2023-01-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_hour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hour',
            new_name='BarberHour',
        ),
    ]
