# Generated by Django 4.1.3 on 2023-01-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_rename_hour_barberhour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarberHour',
        ),
    ]
