# Generated by Django 4.1.3 on 2023-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('barber', '0004_delete_barberhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='barber_hour',
            field=models.ManyToManyField(to='main.barberhour'),
        ),
    ]
