# Generated by Django 4.1.3 on 2023-01-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_barber_barber_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='barber_hour',
        ),
    ]
