# Generated by Django 4.1.3 on 2022-12-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='barber.barber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
