# Generated by Django 4.1.3 on 2023-01-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_barberhour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarberHour',
        ),
    ]
