# Generated by Django 4.1.3 on 2023-01-09 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_date_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
