# Generated by Django 4.1.3 on 2023-01-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0006_remove_barber_barber_hour'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarberHour',
        ),
    ]
